pub enum Action {
    Play,
    Pause,
    Stop,
    Quit,
    MoveToGame { name: String },
    FadeToGame { name: String },
    FadeOut,
    BackInQueue,
    NextInQueue,
    AddToQueue { name: String },
    ResetQueue,
    // Editor stuff tagged on too
    New,
    Load,
    Save,
    SetImageFile,
    SetMusicFile,
    PreviewMusic,
    StopMusic,
}
